---
apiVersion: v1
kind: Service
metadata:
  name: servicemaster
  labels:
    app: master
spec:
  ports:
  - port: 22
    name: master
  clusterIP: None
  selector:
    app: master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: master
  labels:
    app: master
spec:
  serviceName: "servicemaster"
  selector:
    matchLabels:
      app: master
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: <Your image>
        ports:
        - containerPort: 22
          name: master
