---
apiVersion: v1
kind: Service
metadata:
  name: serviceworker
  labels:
    app: worker
spec:
  ports:
  - port: 22
    name: worker
  clusterIP: None
  selector:
    app: worker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
  labels:
    app: worker
spec:
  serviceName: "serviceworker"
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: <Your image>
        ports:
        - containerPort: 22
          name: worker
